# CLEVRER videos: 128 frames, 480x320 resolution. DINOv2-B/14 expects 518x518 inputs.
experiment_group: videosaur
experiment_name: clevrer_dinov2

globals:
  NUM_SLOTS: 7
  SLOT_DIM: 64
  DINO_MODEL: vit_small_patch14_dinov2.lvd142m
  FEAT_DIM: 384
  NUM_PATCHES: 1369
  NUM_GPUS: 1
  BATCH_SIZE_PER_GPU: 4
  TOTAL_BATCH_SIZE: "${mul: ${.NUM_GPUS}, ${.BATCH_SIZE_PER_GPU}}"
  BASE_LR: 0.0001
  SIM_WEIGHT: 0.1
  SIM_TEMP: 0.15

wandb:
  enable: true
  project: videosaur
  name: ${experiment_name}
  group: ${experiment_group}
  tags: [clevrer, dinov2]
  mode: online


trainer:
  max_steps: 100
  log_every_n_steps: 1
  val_check_interval: 10
  gradient_clip_val: 0.05

optimizer:
  name: Adam
  # Scale learning rate by batch size: take base lr once for every 32 samples
  lr: "${eval: 'a / 32 * b', ${globals.TOTAL_BATCH_SIZE}, ${globals.BASE_LR}}"
  lr_scheduler:
    name: exp_decay_with_warmup
    warmup_steps: 10
    decay_steps: ${trainer.max_steps}

model:
  input_type: video
  visualize: true
  visualize_every_n_steps: 100

  losses:
    loss_featrec:
      name: MSELoss
      pred_dims:
        - 0
        - ${globals.FEAT_DIM}
    loss_timesim:
      name: CrossEntropyLoss
      target_key: encoder.vit_block_keys12
      remove_last_n_frames: 1
      pred_dims:
        - ${globals.FEAT_DIM}
        - "${add: ${globals.FEAT_DIM}, ${globals.NUM_PATCHES}}"
      target_transform:
        name: utils.FeatureTimeSimilarity
        softmax: true
        temperature: ${globals.SIM_TEMP}
        threshold: 0.0
  loss_weights:
    loss_timesim: ${globals.SIM_WEIGHT}
    loss_featrec: 1.0

  initializer:
    name: RandomInit
    n_slots: ${globals.NUM_SLOTS}
    dim: ${globals.SLOT_DIM}

  encoder:
    backbone:
      name: TimmExtractor
      model: ${globals.DINO_MODEL}
      features:
      - vit_block12
      - vit_block_keys12
      frozen: true
      pretrained: true
    output_transform:
      name: networks.two_layer_mlp
      inp_dim: ${globals.FEAT_DIM}
      outp_dim: ${globals.SLOT_DIM}
      hidden_dim: "${mul: ${globals.FEAT_DIM}, 2}"
      layer_norm: true

  grouper:
    name: SlotAttention
    inp_dim: ${globals.SLOT_DIM}
    slot_dim: ${globals.SLOT_DIM}
    n_iters: 2
    use_mlp: false

  latent_processor:
    first_step_corrector_args:
      n_iters: 3

  decoder:
    name: SlotMixerDecoder
    inp_dim: ${globals.SLOT_DIM}
    embed_dim: ${globals.SLOT_DIM}
    outp_dim: "${add: ${globals.FEAT_DIM}, ${globals.NUM_PATCHES}}"
    n_patches: ${globals.NUM_PATCHES}
    allocator:
      name: TransformerEncoder
      dim: ${globals.SLOT_DIM}
      memory_dim: ${globals.SLOT_DIM}
      n_blocks: 3
      n_heads: 4
    renderer:
      name: MLP
      inp_dim: ${globals.SLOT_DIM}
      outp_dim: 1024
      hidden_dims: [1024, 1024]
      final_activation: true
    renderer_dim: 1024
    use_layer_norms: true
    pos_embed_mode: add

  predictor:
    name: networks.TransformerEncoder
    dim: ${globals.SLOT_DIM}
    n_blocks: 1
    n_heads: 4

val_metrics: null

dataset:
  train_shards: "../../scratch/clevrer_wds/train/clevrer-train-{000000..000099}.tar"
  val_shards: "../../scratch/clevrer_wds/validation/clevrer-train-{000100..000149}.tar"
  batch_size: ${globals.BATCH_SIZE_PER_GPU}
  val_batch_size: 4
  val_size: 200
  num_workers: 2 # increase this if you have more CPU cores
  num_val_workers: 2 
  train_pipeline:
    chunk_size: 4
    keys: [video]
    sample_one_chunk_per_video: true
    transforms:
      name: clevrer_train
      type: video
      crop_type: short_side_resize_random
      input_size: 518
      h_flip_prob: 0.5
  val_pipeline:
    use_chunks: true
    chunk_size: 6
    keys: [video]
    transforms:
      name: clevrer_val
      type: video
      crop_type: central
      input_size: 518
      use_segmentations: false
