checkpoint: /cs/data/people/hnam16/.stable_worldmodel/artifacts/oc-checkpoints/step=100000_weight01_lr1e-4_clevrer.ckpt
model_config: videosaur/configs/videosaur/clevrer_dinov2_hf.yml
n_slots: 7
input:
  path: /cs/data/people/hnam16/.stable_worldmodel/clevrer_val/videos/12000_pixels.mp4
  type: video
  transforms:
    dataset_type: video
    input_size: 196
output:
  save_path: result_video/video_10000_masks_hf_1e-4_01.mp4